In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0,1,1,0]]).T
print(X , "shape of X is" , X.shape)
print(Y, "shape of Y is" , Y.shape)

[[0 0]
 [0 1]
 [1 0]
 [1 1]] shape of X is (4, 2)
[[0]
 [1]
 [1]
 [0]] shape of Y is (4, 1)


In [3]:

def sigmoid(x):
    return 1/(1+np.exp(-x))


In [4]:
def derivative_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))
    

In [5]:
# Weights and bias initialization
wh = 2 * np.random.rand(2, 2) - 1  # Weights for hidden layer
bh = 2 * np.random.rand(1, 2) - 1  # Bias for hidden layer (one bias per hidden neuron)
wo = 2 * np.random.rand(2, 1) - 1  # Weights for output layer
bo = 2 * np.random.rand(1, 1) - 1  # Bias for output layer

lerning_rate = 0.1

In [6]:
# Updated Training Loop
for iteration in range(100000):
    # Forward Propagation
    input_layer = X
    hidden_layer_input = np.dot(input_layer, wh) + bh
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, wo) + bo
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation - Output Layer
    # Error: (Predicted - Actual)
    error_output_layer = predicted_output - Y
    # Gradient: Error * derivative of sigmoid at the output
    d_output = error_output_layer * (predicted_output * (1 - predicted_output))

    # Backpropagation - Hidden Layer
    # Error: Contribution of hidden neurons to output error
    error_hidden_layer = np.dot(d_output, wo.T)
    # Gradient: Error * derivative of sigmoid at the hidden layer
    d_hidden = error_hidden_layer * (hidden_layer_output * (1 - hidden_layer_output))

    # Weight and Bias Updates
    # FIX: Dot product of hidden layer output and the output gradient
    changes_output_layer = np.dot(hidden_layer_output.T, d_output)
    changes_output_bias = np.sum(d_output, axis=0, keepdims=True)

    changes_hidden_layer = np.dot(input_layer.T, d_hidden)
    changes_hidden_bias = np.sum(d_hidden, axis=0, keepdims=True)

    # Gradient Descent update
    wo = wo - lerning_rate * changes_output_layer
    bo = bo - lerning_rate * changes_output_bias
    wh = wh - lerning_rate * changes_hidden_layer
    bh = bh - lerning_rate * changes_hidden_bias

In [7]:
input_layer = X
hidden_layer_input = np.dot(input_layer, wh) + bh
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, wo) + bo
predicted_output = sigmoid(output_layer_input)


print("wh wb wo bo ")
print(wh)
print(bh)
print(wo)
print(bo)

print("Predicted output after training:")
print(predicted_output)

wh wb wo bo 
[[-4.9737357  -7.03587307]
 [-4.97417725 -7.03890921]]
[[7.40533866 2.92667868]]
[[ 10.46644644]
 [-10.50060127]]
[[-4.99917444]]
Predicted output after training:
[[0.01092486]
 [0.98848087]
 [0.98847902]
 [0.01425852]]
