In [37]:
import numpy as np

In [38]:
X = np.array([[0,0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0,1,1,0]]).T
print(X , "shape of X is" , X.shape)
print(Y, "shape of Y is" , Y.shape)

[[0 0]
 [0 1]
 [1 0]
 [1 1]] shape of X is (4, 2)
[[0]
 [1]
 [1]
 [0]] shape of Y is (4, 1)


In [39]:

def sigmoid(x):
    return 1/(1+np.exp(-x))


In [40]:
def derivative_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))
    

In [41]:
# Weights and bias initialization
wh = 2 * np.random.rand(2, 2) - 1  # Weights for hidden layer
bh = 2 * np.random.rand(1, 2) - 1  # Bias for hidden layer (one bias per hidden neuron)
wo = 2 * np.random.rand(2, 1) - 1  # Weights for output layer
bo = 2 * np.random.rand(1, 1) - 1  # Bias for output layer

lerning_rate = 0.1

In [42]:
    # Forward Propagation
for iteration in range(10000):
    input_layer = X
    hidden_layer_input = np.dot(input_layer, wh) + bh
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, wo) + bo
    predicted_output = sigmoid(output_layer_input)

    first_term_output_layer = predicted_output - Y
    second_term_output_layer = derivative_sigmoid(output_layer_input)
    first_two_terms_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_terms_output_layer, wo.T)
    second_term_hidden_layer = derivative_sigmoid(hidden_layer_input)
    first_two_terms_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output_layer = np.dot(first_two_terms_output_layer.T, first_two_terms_output_layer)
    changes_output_bias = np.sum(first_two_terms_output_layer, axis=0, keepdims=True)

    changes_hidden_layer = np.dot(input_layer.T, first_two_terms_hidden_layer)
    changes_hidden_bias = np.sum(first_two_terms_hidden_layer, axis=0, keepdims=True)

    wo = wo - lerning_rate * changes_output_layer
    bo = bo - lerning_rate * changes_output_bias
    wh = wh - lerning_rate * changes_hidden_layer
    bh = bh - lerning_rate * changes_hidden_bias

In [43]:
input_layer = X
hidden_layer_input = np.dot(input_layer, wh) + bh
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, wo) + bo
predicted_output = sigmoid(output_layer_input)


print("wh wb wo bo ")
print(wh)
print(bh)
print(wo)
print(bo)

print("Predicted output after training:")
print(predicted_output)

wh wb wo bo 
[[-5.56517128  4.39339878]
 [-5.56515537  4.39339434]]
[[ 2.14567576 -6.70590362]]
[[-6.82941638]
 [-6.67704807]]
[[3.41927924]]
Predicted output after training:
[[0.06279586]
 [0.93094455]
 [0.93094461]
 [0.07462768]]
